---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/apps/linkos"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "api"
  - package-ecosystem: npm
    directory: "/apps/dashboard"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "dashboard"
  - package-ecosystem: npm
    directory: "/apps/extension"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "extension"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "dockerfile"
